#ifndef CONSTS_H
#define CONSTS_H

enum Constants {
    WORLD_LENGTH = 100,
    WORLD_WIDTH = 200,
    ENTITY_LIMIT = 128,
    STACK_LIMIT = 20,
    UNINITIALIZED_8BIT = UINT8_MAX,
    UNINITIALIZED_16BIT = UINT16_MAX,
    UNINITIALIZED_32BIT = UINT32_MAX
};

#endif